databases:
  - name: udaymart-db
    plan: free
    databaseName: udaymart
    user: udaymart

services:
  - type: web
    name: udaymart
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python setup_data.py
    startCommand: gunicorn udaymart.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: udaymart-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
